# Global configuration for all applications
# defaults and constants


global:
  namespace: default
  defaultCluster: https://kubernetes.default.svc
projects:
  default: default
  
namespaces:
  netbox:
    enabled: false
    namespace: netbox
  elastic:
    enabled: false
    namespace: elastic

 # applications with parameters 
applications:
  netbox:
    enabled: true
    name: netbox
    description: netbox helm chart
    destination:
      namespace: netbox
      server: null
    project: null  
    enableCascade: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    source:
      namespace: netbox
      chart: netbox
      repoURL: https://charts.boo.tc  
      path: null
      targetRevision: 2.8.3
      helmValuesOrFile: |
        helm:
              valueFiles: 
              - netbox-values.yaml
  fluent-bit:
    enabled: true
    name: fluent-bit
    description: fluent-bit helm chart
    destination:
      namespace: ops
      server: null
    project: null  
    enableCascade: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    source:
      namespace: ops
      chart: fluent-bit
      repoURL: https://kubernetes-charts.storage.googleapis.com
      path: null
      targetRevision: 2.8.12 
      helm:
        values: |
          image:
            fluent_bit:
              repository: fluent/fluent-bit
              tag: 1.3.8
              pullPolicy: Always
          metrics:
            enabled: true           