# Global configuration for all applications
# defaults and constants


global:
  namespace: default
  defaultCluster: https://kubernetes.default.svc
projects:
  default: default
  
namespaces:
  netbox:
    enabled: true
    namespace: netbox
  elastic:
    enabled: false
    namespace: elastic

 # applications with parameters 
applications:
  netbox:
    enabled: true
    name: netbox
    description: netbox helm chart
    destination:
      namespace: netbox
      server: null
    project: null  
    enableCascade: true
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
    source:
      namespace: netbox
      chart: netbox
      repoURL: https://charts.boo.tc  
      path: null
      targetRevision: 2.8.3
      helmValuesFile: |
      helm:
        valueFiles: 
        - netbox-values.yaml 
        