{{- range .Values.applications }}
  {{- if .enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  {{- if .enableCascade }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  {{- end }}    
  name: {{ .name }}
  namespace: 
spec:
  source:
    chart: {{ .source.chart }}
    helm:
      valueFiles:
      - values.yaml
    repoURL: {{ .source.repoURL }}
    targetRevision: {{ .targetRevision }}
  destination: 
    namespace: {{ .destination.namespace | default $.Values.global.namespace }}
    server: {{  .destination.server | default $.Values.global.defaultCluster }}
  project: {{ .project | default $.Values.projects.default }}
  syncPolicy:
    automated:
      selfHeal: {{ syncPolicy.automated.selfHeal | default true  }}  
      prune:   {{ syncPolicy.automated.prune | default false }}  
  {{- end }}
{{- end }}