apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: elasticsearch
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: elasticsearch
  syncPolicy:
    automated:
      selfHeal: true  
  source:
    repoURL: https://kubernetes-charts.storage.googleapis.com
    chart: fluent-bit
    targetRevision: 2.8.12
    helm:
      values: |
        image:
          fluent_bit:
            repository: fluent/fluent-bit
            tag: 1.3.8
            pullPolicy: Always
        metrics:
          enabled: true
