apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seed-applications
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
      - values.yaml
    path: continuous-integration
    repoURL: https://github.com/polarpoint-io/argocd-shared-services-helm-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}